/*
NATS Token Exchange

Exchanges OAuth tokens for NATS tokens

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Permissions Permissions are used to restrict subject access, either on a user or for everyone on a server by default
type Permissions struct {
	Pub *Permission `json:"pub,omitempty"`
	Resp *ResponsePermission `json:"resp,omitempty"`
	Sub *Permission `json:"sub,omitempty"`
}

// NewPermissions instantiates a new Permissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissions() *Permissions {
	this := Permissions{}
	return &this
}

// NewPermissionsWithDefaults instantiates a new Permissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsWithDefaults() *Permissions {
	this := Permissions{}
	return &this
}

// GetPub returns the Pub field value if set, zero value otherwise.
func (o *Permissions) GetPub() Permission {
	if o == nil || o.Pub == nil {
		var ret Permission
		return ret
	}
	return *o.Pub
}

// GetPubOk returns a tuple with the Pub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Permissions) GetPubOk() (*Permission, bool) {
	if o == nil || o.Pub == nil {
		return nil, false
	}
	return o.Pub, true
}

// HasPub returns a boolean if a field has been set.
func (o *Permissions) HasPub() bool {
	if o != nil && o.Pub != nil {
		return true
	}

	return false
}

// SetPub gets a reference to the given Permission and assigns it to the Pub field.
func (o *Permissions) SetPub(v Permission) {
	o.Pub = &v
}

// GetResp returns the Resp field value if set, zero value otherwise.
func (o *Permissions) GetResp() ResponsePermission {
	if o == nil || o.Resp == nil {
		var ret ResponsePermission
		return ret
	}
	return *o.Resp
}

// GetRespOk returns a tuple with the Resp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Permissions) GetRespOk() (*ResponsePermission, bool) {
	if o == nil || o.Resp == nil {
		return nil, false
	}
	return o.Resp, true
}

// HasResp returns a boolean if a field has been set.
func (o *Permissions) HasResp() bool {
	if o != nil && o.Resp != nil {
		return true
	}

	return false
}

// SetResp gets a reference to the given ResponsePermission and assigns it to the Resp field.
func (o *Permissions) SetResp(v ResponsePermission) {
	o.Resp = &v
}

// GetSub returns the Sub field value if set, zero value otherwise.
func (o *Permissions) GetSub() Permission {
	if o == nil || o.Sub == nil {
		var ret Permission
		return ret
	}
	return *o.Sub
}

// GetSubOk returns a tuple with the Sub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Permissions) GetSubOk() (*Permission, bool) {
	if o == nil || o.Sub == nil {
		return nil, false
	}
	return o.Sub, true
}

// HasSub returns a boolean if a field has been set.
func (o *Permissions) HasSub() bool {
	if o != nil && o.Sub != nil {
		return true
	}

	return false
}

// SetSub gets a reference to the given Permission and assigns it to the Sub field.
func (o *Permissions) SetSub(v Permission) {
	o.Sub = &v
}

func (o Permissions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pub != nil {
		toSerialize["pub"] = o.Pub
	}
	if o.Resp != nil {
		toSerialize["resp"] = o.Resp
	}
	if o.Sub != nil {
		toSerialize["sub"] = o.Sub
	}
	return json.Marshal(toSerialize)
}

type NullablePermissions struct {
	value *Permissions
	isSet bool
}

func (v NullablePermissions) Get() *Permissions {
	return v.value
}

func (v *NullablePermissions) Set(val *Permissions) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissions(val *Permissions) *NullablePermissions {
	return &NullablePermissions{value: val, isSet: true}
}

func (v NullablePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


