/*
NATS Token Exchange

Exchanges OAuth tokens for NATS tokens

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Limits Limits are used to control acccess for users and importing accounts
type Limits struct {
	Data *int64 `json:"data,omitempty"`
	Payload *int64 `json:"payload,omitempty"`
	// TagList is a unique array of lower case strings All tag list methods lower case the strings in the arguments
	Src []string `json:"src,omitempty"`
	Subs *int64 `json:"subs,omitempty"`
	Times []TimeRange `json:"times,omitempty"`
	TimesLocation *string `json:"times_location,omitempty"`
}

// NewLimits instantiates a new Limits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLimits() *Limits {
	this := Limits{}
	return &this
}

// NewLimitsWithDefaults instantiates a new Limits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLimitsWithDefaults() *Limits {
	this := Limits{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Limits) GetData() int64 {
	if o == nil || o.Data == nil {
		var ret int64
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetDataOk() (*int64, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Limits) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given int64 and assigns it to the Data field.
func (o *Limits) SetData(v int64) {
	o.Data = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *Limits) GetPayload() int64 {
	if o == nil || o.Payload == nil {
		var ret int64
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetPayloadOk() (*int64, bool) {
	if o == nil || o.Payload == nil {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *Limits) HasPayload() bool {
	if o != nil && o.Payload != nil {
		return true
	}

	return false
}

// SetPayload gets a reference to the given int64 and assigns it to the Payload field.
func (o *Limits) SetPayload(v int64) {
	o.Payload = &v
}

// GetSrc returns the Src field value if set, zero value otherwise.
func (o *Limits) GetSrc() []string {
	if o == nil || o.Src == nil {
		var ret []string
		return ret
	}
	return o.Src
}

// GetSrcOk returns a tuple with the Src field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetSrcOk() ([]string, bool) {
	if o == nil || o.Src == nil {
		return nil, false
	}
	return o.Src, true
}

// HasSrc returns a boolean if a field has been set.
func (o *Limits) HasSrc() bool {
	if o != nil && o.Src != nil {
		return true
	}

	return false
}

// SetSrc gets a reference to the given []string and assigns it to the Src field.
func (o *Limits) SetSrc(v []string) {
	o.Src = v
}

// GetSubs returns the Subs field value if set, zero value otherwise.
func (o *Limits) GetSubs() int64 {
	if o == nil || o.Subs == nil {
		var ret int64
		return ret
	}
	return *o.Subs
}

// GetSubsOk returns a tuple with the Subs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetSubsOk() (*int64, bool) {
	if o == nil || o.Subs == nil {
		return nil, false
	}
	return o.Subs, true
}

// HasSubs returns a boolean if a field has been set.
func (o *Limits) HasSubs() bool {
	if o != nil && o.Subs != nil {
		return true
	}

	return false
}

// SetSubs gets a reference to the given int64 and assigns it to the Subs field.
func (o *Limits) SetSubs(v int64) {
	o.Subs = &v
}

// GetTimes returns the Times field value if set, zero value otherwise.
func (o *Limits) GetTimes() []TimeRange {
	if o == nil || o.Times == nil {
		var ret []TimeRange
		return ret
	}
	return o.Times
}

// GetTimesOk returns a tuple with the Times field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetTimesOk() ([]TimeRange, bool) {
	if o == nil || o.Times == nil {
		return nil, false
	}
	return o.Times, true
}

// HasTimes returns a boolean if a field has been set.
func (o *Limits) HasTimes() bool {
	if o != nil && o.Times != nil {
		return true
	}

	return false
}

// SetTimes gets a reference to the given []TimeRange and assigns it to the Times field.
func (o *Limits) SetTimes(v []TimeRange) {
	o.Times = v
}

// GetTimesLocation returns the TimesLocation field value if set, zero value otherwise.
func (o *Limits) GetTimesLocation() string {
	if o == nil || o.TimesLocation == nil {
		var ret string
		return ret
	}
	return *o.TimesLocation
}

// GetTimesLocationOk returns a tuple with the TimesLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Limits) GetTimesLocationOk() (*string, bool) {
	if o == nil || o.TimesLocation == nil {
		return nil, false
	}
	return o.TimesLocation, true
}

// HasTimesLocation returns a boolean if a field has been set.
func (o *Limits) HasTimesLocation() bool {
	if o != nil && o.TimesLocation != nil {
		return true
	}

	return false
}

// SetTimesLocation gets a reference to the given string and assigns it to the TimesLocation field.
func (o *Limits) SetTimesLocation(v string) {
	o.TimesLocation = &v
}

func (o Limits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	if o.Src != nil {
		toSerialize["src"] = o.Src
	}
	if o.Subs != nil {
		toSerialize["subs"] = o.Subs
	}
	if o.Times != nil {
		toSerialize["times"] = o.Times
	}
	if o.TimesLocation != nil {
		toSerialize["times_location"] = o.TimesLocation
	}
	return json.Marshal(toSerialize)
}

type NullableLimits struct {
	value *Limits
	isSet bool
}

func (v NullableLimits) Get() *Limits {
	return v.value
}

func (v *NullableLimits) Set(val *Limits) {
	v.value = val
	v.isSet = true
}

func (v NullableLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLimits(val *Limits) *NullableLimits {
	return &NullableLimits{value: val, isSet: true}
}

func (v NullableLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


