/*
NATS Token Exchange

Exchanges OAuth tokens for NATS tokens

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokenx

import (
	"encoding/json"
)

// User User defines the user specific data in a user JWT
type User struct {
	// StringList is a wrapper for an array of strings
	AllowedConnectionTypes []string `json:"allowed_connection_types,omitempty"`
	BearerToken *bool `json:"bearer_token,omitempty"`
	Data *int64 `json:"data,omitempty"`
	// IssuerAccount stores the public key for the account the issuer represents. When set, the claim was issued by a signing key.
	IssuerAccount *string `json:"issuer_account,omitempty"`
	Payload *int64 `json:"payload,omitempty"`
	Pub *Permission `json:"pub,omitempty"`
	Resp *ResponsePermission `json:"resp,omitempty"`
	// TagList is a unique array of lower case strings All tag list methods lower case the strings in the arguments
	Src []string `json:"src,omitempty"`
	Sub *Permission `json:"sub,omitempty"`
	Subs *int64 `json:"subs,omitempty"`
	// TagList is a unique array of lower case strings All tag list methods lower case the strings in the arguments
	Tags []string `json:"tags,omitempty"`
	Times []TimeRange `json:"times,omitempty"`
	TimesLocation *string `json:"times_location,omitempty"`
	// ClaimType is used to indicate the type of JWT being stored in a Claim
	Type *string `json:"type,omitempty"`
	Version *int64 `json:"version,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser() *User {
	this := User{}
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetAllowedConnectionTypes returns the AllowedConnectionTypes field value if set, zero value otherwise.
func (o *User) GetAllowedConnectionTypes() []string {
	if o == nil || o.AllowedConnectionTypes == nil {
		var ret []string
		return ret
	}
	return o.AllowedConnectionTypes
}

// GetAllowedConnectionTypesOk returns a tuple with the AllowedConnectionTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAllowedConnectionTypesOk() ([]string, bool) {
	if o == nil || o.AllowedConnectionTypes == nil {
		return nil, false
	}
	return o.AllowedConnectionTypes, true
}

// HasAllowedConnectionTypes returns a boolean if a field has been set.
func (o *User) HasAllowedConnectionTypes() bool {
	if o != nil && o.AllowedConnectionTypes != nil {
		return true
	}

	return false
}

// SetAllowedConnectionTypes gets a reference to the given []string and assigns it to the AllowedConnectionTypes field.
func (o *User) SetAllowedConnectionTypes(v []string) {
	o.AllowedConnectionTypes = v
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *User) GetBearerToken() bool {
	if o == nil || o.BearerToken == nil {
		var ret bool
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetBearerTokenOk() (*bool, bool) {
	if o == nil || o.BearerToken == nil {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *User) HasBearerToken() bool {
	if o != nil && o.BearerToken != nil {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given bool and assigns it to the BearerToken field.
func (o *User) SetBearerToken(v bool) {
	o.BearerToken = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *User) GetData() int64 {
	if o == nil || o.Data == nil {
		var ret int64
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDataOk() (*int64, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *User) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given int64 and assigns it to the Data field.
func (o *User) SetData(v int64) {
	o.Data = &v
}

// GetIssuerAccount returns the IssuerAccount field value if set, zero value otherwise.
func (o *User) GetIssuerAccount() string {
	if o == nil || o.IssuerAccount == nil {
		var ret string
		return ret
	}
	return *o.IssuerAccount
}

// GetIssuerAccountOk returns a tuple with the IssuerAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIssuerAccountOk() (*string, bool) {
	if o == nil || o.IssuerAccount == nil {
		return nil, false
	}
	return o.IssuerAccount, true
}

// HasIssuerAccount returns a boolean if a field has been set.
func (o *User) HasIssuerAccount() bool {
	if o != nil && o.IssuerAccount != nil {
		return true
	}

	return false
}

// SetIssuerAccount gets a reference to the given string and assigns it to the IssuerAccount field.
func (o *User) SetIssuerAccount(v string) {
	o.IssuerAccount = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *User) GetPayload() int64 {
	if o == nil || o.Payload == nil {
		var ret int64
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPayloadOk() (*int64, bool) {
	if o == nil || o.Payload == nil {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *User) HasPayload() bool {
	if o != nil && o.Payload != nil {
		return true
	}

	return false
}

// SetPayload gets a reference to the given int64 and assigns it to the Payload field.
func (o *User) SetPayload(v int64) {
	o.Payload = &v
}

// GetPub returns the Pub field value if set, zero value otherwise.
func (o *User) GetPub() Permission {
	if o == nil || o.Pub == nil {
		var ret Permission
		return ret
	}
	return *o.Pub
}

// GetPubOk returns a tuple with the Pub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPubOk() (*Permission, bool) {
	if o == nil || o.Pub == nil {
		return nil, false
	}
	return o.Pub, true
}

// HasPub returns a boolean if a field has been set.
func (o *User) HasPub() bool {
	if o != nil && o.Pub != nil {
		return true
	}

	return false
}

// SetPub gets a reference to the given Permission and assigns it to the Pub field.
func (o *User) SetPub(v Permission) {
	o.Pub = &v
}

// GetResp returns the Resp field value if set, zero value otherwise.
func (o *User) GetResp() ResponsePermission {
	if o == nil || o.Resp == nil {
		var ret ResponsePermission
		return ret
	}
	return *o.Resp
}

// GetRespOk returns a tuple with the Resp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRespOk() (*ResponsePermission, bool) {
	if o == nil || o.Resp == nil {
		return nil, false
	}
	return o.Resp, true
}

// HasResp returns a boolean if a field has been set.
func (o *User) HasResp() bool {
	if o != nil && o.Resp != nil {
		return true
	}

	return false
}

// SetResp gets a reference to the given ResponsePermission and assigns it to the Resp field.
func (o *User) SetResp(v ResponsePermission) {
	o.Resp = &v
}

// GetSrc returns the Src field value if set, zero value otherwise.
func (o *User) GetSrc() []string {
	if o == nil || o.Src == nil {
		var ret []string
		return ret
	}
	return o.Src
}

// GetSrcOk returns a tuple with the Src field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSrcOk() ([]string, bool) {
	if o == nil || o.Src == nil {
		return nil, false
	}
	return o.Src, true
}

// HasSrc returns a boolean if a field has been set.
func (o *User) HasSrc() bool {
	if o != nil && o.Src != nil {
		return true
	}

	return false
}

// SetSrc gets a reference to the given []string and assigns it to the Src field.
func (o *User) SetSrc(v []string) {
	o.Src = v
}

// GetSub returns the Sub field value if set, zero value otherwise.
func (o *User) GetSub() Permission {
	if o == nil || o.Sub == nil {
		var ret Permission
		return ret
	}
	return *o.Sub
}

// GetSubOk returns a tuple with the Sub field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubOk() (*Permission, bool) {
	if o == nil || o.Sub == nil {
		return nil, false
	}
	return o.Sub, true
}

// HasSub returns a boolean if a field has been set.
func (o *User) HasSub() bool {
	if o != nil && o.Sub != nil {
		return true
	}

	return false
}

// SetSub gets a reference to the given Permission and assigns it to the Sub field.
func (o *User) SetSub(v Permission) {
	o.Sub = &v
}

// GetSubs returns the Subs field value if set, zero value otherwise.
func (o *User) GetSubs() int64 {
	if o == nil || o.Subs == nil {
		var ret int64
		return ret
	}
	return *o.Subs
}

// GetSubsOk returns a tuple with the Subs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubsOk() (*int64, bool) {
	if o == nil || o.Subs == nil {
		return nil, false
	}
	return o.Subs, true
}

// HasSubs returns a boolean if a field has been set.
func (o *User) HasSubs() bool {
	if o != nil && o.Subs != nil {
		return true
	}

	return false
}

// SetSubs gets a reference to the given int64 and assigns it to the Subs field.
func (o *User) SetSubs(v int64) {
	o.Subs = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *User) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *User) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *User) SetTags(v []string) {
	o.Tags = v
}

// GetTimes returns the Times field value if set, zero value otherwise.
func (o *User) GetTimes() []TimeRange {
	if o == nil || o.Times == nil {
		var ret []TimeRange
		return ret
	}
	return o.Times
}

// GetTimesOk returns a tuple with the Times field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTimesOk() ([]TimeRange, bool) {
	if o == nil || o.Times == nil {
		return nil, false
	}
	return o.Times, true
}

// HasTimes returns a boolean if a field has been set.
func (o *User) HasTimes() bool {
	if o != nil && o.Times != nil {
		return true
	}

	return false
}

// SetTimes gets a reference to the given []TimeRange and assigns it to the Times field.
func (o *User) SetTimes(v []TimeRange) {
	o.Times = v
}

// GetTimesLocation returns the TimesLocation field value if set, zero value otherwise.
func (o *User) GetTimesLocation() string {
	if o == nil || o.TimesLocation == nil {
		var ret string
		return ret
	}
	return *o.TimesLocation
}

// GetTimesLocationOk returns a tuple with the TimesLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTimesLocationOk() (*string, bool) {
	if o == nil || o.TimesLocation == nil {
		return nil, false
	}
	return o.TimesLocation, true
}

// HasTimesLocation returns a boolean if a field has been set.
func (o *User) HasTimesLocation() bool {
	if o != nil && o.TimesLocation != nil {
		return true
	}

	return false
}

// SetTimesLocation gets a reference to the given string and assigns it to the TimesLocation field.
func (o *User) SetTimesLocation(v string) {
	o.TimesLocation = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *User) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *User) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *User) SetType(v string) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *User) GetVersion() int64 {
	if o == nil || o.Version == nil {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetVersionOk() (*int64, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *User) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *User) SetVersion(v int64) {
	o.Version = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedConnectionTypes != nil {
		toSerialize["allowed_connection_types"] = o.AllowedConnectionTypes
	}
	if o.BearerToken != nil {
		toSerialize["bearer_token"] = o.BearerToken
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.IssuerAccount != nil {
		toSerialize["issuer_account"] = o.IssuerAccount
	}
	if o.Payload != nil {
		toSerialize["payload"] = o.Payload
	}
	if o.Pub != nil {
		toSerialize["pub"] = o.Pub
	}
	if o.Resp != nil {
		toSerialize["resp"] = o.Resp
	}
	if o.Src != nil {
		toSerialize["src"] = o.Src
	}
	if o.Sub != nil {
		toSerialize["sub"] = o.Sub
	}
	if o.Subs != nil {
		toSerialize["subs"] = o.Subs
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Times != nil {
		toSerialize["times"] = o.Times
	}
	if o.TimesLocation != nil {
		toSerialize["times_location"] = o.TimesLocation
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


