/*
NATS Token Exchange

Exchanges OAuth tokens for NATS tokens

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokenx

import (
	"encoding/json"
)

// JetStreamLimits struct for JetStreamLimits
type JetStreamLimits struct {
	Consumer *int64 `json:"consumer,omitempty"`
	DiskStorage *int64 `json:"disk_storage,omitempty"`
	MaxBytesRequired *bool `json:"max_bytes_required,omitempty"`
	MemStorage *int64 `json:"mem_storage,omitempty"`
	Streams *int64 `json:"streams,omitempty"`
}

// NewJetStreamLimits instantiates a new JetStreamLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJetStreamLimits() *JetStreamLimits {
	this := JetStreamLimits{}
	return &this
}

// NewJetStreamLimitsWithDefaults instantiates a new JetStreamLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJetStreamLimitsWithDefaults() *JetStreamLimits {
	this := JetStreamLimits{}
	return &this
}

// GetConsumer returns the Consumer field value if set, zero value otherwise.
func (o *JetStreamLimits) GetConsumer() int64 {
	if o == nil || o.Consumer == nil {
		var ret int64
		return ret
	}
	return *o.Consumer
}

// GetConsumerOk returns a tuple with the Consumer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JetStreamLimits) GetConsumerOk() (*int64, bool) {
	if o == nil || o.Consumer == nil {
		return nil, false
	}
	return o.Consumer, true
}

// HasConsumer returns a boolean if a field has been set.
func (o *JetStreamLimits) HasConsumer() bool {
	if o != nil && o.Consumer != nil {
		return true
	}

	return false
}

// SetConsumer gets a reference to the given int64 and assigns it to the Consumer field.
func (o *JetStreamLimits) SetConsumer(v int64) {
	o.Consumer = &v
}

// GetDiskStorage returns the DiskStorage field value if set, zero value otherwise.
func (o *JetStreamLimits) GetDiskStorage() int64 {
	if o == nil || o.DiskStorage == nil {
		var ret int64
		return ret
	}
	return *o.DiskStorage
}

// GetDiskStorageOk returns a tuple with the DiskStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JetStreamLimits) GetDiskStorageOk() (*int64, bool) {
	if o == nil || o.DiskStorage == nil {
		return nil, false
	}
	return o.DiskStorage, true
}

// HasDiskStorage returns a boolean if a field has been set.
func (o *JetStreamLimits) HasDiskStorage() bool {
	if o != nil && o.DiskStorage != nil {
		return true
	}

	return false
}

// SetDiskStorage gets a reference to the given int64 and assigns it to the DiskStorage field.
func (o *JetStreamLimits) SetDiskStorage(v int64) {
	o.DiskStorage = &v
}

// GetMaxBytesRequired returns the MaxBytesRequired field value if set, zero value otherwise.
func (o *JetStreamLimits) GetMaxBytesRequired() bool {
	if o == nil || o.MaxBytesRequired == nil {
		var ret bool
		return ret
	}
	return *o.MaxBytesRequired
}

// GetMaxBytesRequiredOk returns a tuple with the MaxBytesRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JetStreamLimits) GetMaxBytesRequiredOk() (*bool, bool) {
	if o == nil || o.MaxBytesRequired == nil {
		return nil, false
	}
	return o.MaxBytesRequired, true
}

// HasMaxBytesRequired returns a boolean if a field has been set.
func (o *JetStreamLimits) HasMaxBytesRequired() bool {
	if o != nil && o.MaxBytesRequired != nil {
		return true
	}

	return false
}

// SetMaxBytesRequired gets a reference to the given bool and assigns it to the MaxBytesRequired field.
func (o *JetStreamLimits) SetMaxBytesRequired(v bool) {
	o.MaxBytesRequired = &v
}

// GetMemStorage returns the MemStorage field value if set, zero value otherwise.
func (o *JetStreamLimits) GetMemStorage() int64 {
	if o == nil || o.MemStorage == nil {
		var ret int64
		return ret
	}
	return *o.MemStorage
}

// GetMemStorageOk returns a tuple with the MemStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JetStreamLimits) GetMemStorageOk() (*int64, bool) {
	if o == nil || o.MemStorage == nil {
		return nil, false
	}
	return o.MemStorage, true
}

// HasMemStorage returns a boolean if a field has been set.
func (o *JetStreamLimits) HasMemStorage() bool {
	if o != nil && o.MemStorage != nil {
		return true
	}

	return false
}

// SetMemStorage gets a reference to the given int64 and assigns it to the MemStorage field.
func (o *JetStreamLimits) SetMemStorage(v int64) {
	o.MemStorage = &v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *JetStreamLimits) GetStreams() int64 {
	if o == nil || o.Streams == nil {
		var ret int64
		return ret
	}
	return *o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JetStreamLimits) GetStreamsOk() (*int64, bool) {
	if o == nil || o.Streams == nil {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *JetStreamLimits) HasStreams() bool {
	if o != nil && o.Streams != nil {
		return true
	}

	return false
}

// SetStreams gets a reference to the given int64 and assigns it to the Streams field.
func (o *JetStreamLimits) SetStreams(v int64) {
	o.Streams = &v
}

func (o JetStreamLimits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Consumer != nil {
		toSerialize["consumer"] = o.Consumer
	}
	if o.DiskStorage != nil {
		toSerialize["disk_storage"] = o.DiskStorage
	}
	if o.MaxBytesRequired != nil {
		toSerialize["max_bytes_required"] = o.MaxBytesRequired
	}
	if o.MemStorage != nil {
		toSerialize["mem_storage"] = o.MemStorage
	}
	if o.Streams != nil {
		toSerialize["streams"] = o.Streams
	}
	return json.Marshal(toSerialize)
}

type NullableJetStreamLimits struct {
	value *JetStreamLimits
	isSet bool
}

func (v NullableJetStreamLimits) Get() *JetStreamLimits {
	return v.value
}

func (v *NullableJetStreamLimits) Set(val *JetStreamLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableJetStreamLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableJetStreamLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJetStreamLimits(val *JetStreamLimits) *NullableJetStreamLimits {
	return &NullableJetStreamLimits{value: val, isSet: true}
}

func (v NullableJetStreamLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJetStreamLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


