/*
NATS Token Exchange

Exchanges OAuth tokens for NATS tokens

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AccountLimits struct for AccountLimits
type AccountLimits struct {
	Conn *int64 `json:"conn,omitempty"`
	Exports *int64 `json:"exports,omitempty"`
	Imports *int64 `json:"imports,omitempty"`
	Leaf *int64 `json:"leaf,omitempty"`
	Wildcards *bool `json:"wildcards,omitempty"`
}

// NewAccountLimits instantiates a new AccountLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountLimits() *AccountLimits {
	this := AccountLimits{}
	return &this
}

// NewAccountLimitsWithDefaults instantiates a new AccountLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountLimitsWithDefaults() *AccountLimits {
	this := AccountLimits{}
	return &this
}

// GetConn returns the Conn field value if set, zero value otherwise.
func (o *AccountLimits) GetConn() int64 {
	if o == nil || o.Conn == nil {
		var ret int64
		return ret
	}
	return *o.Conn
}

// GetConnOk returns a tuple with the Conn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetConnOk() (*int64, bool) {
	if o == nil || o.Conn == nil {
		return nil, false
	}
	return o.Conn, true
}

// HasConn returns a boolean if a field has been set.
func (o *AccountLimits) HasConn() bool {
	if o != nil && o.Conn != nil {
		return true
	}

	return false
}

// SetConn gets a reference to the given int64 and assigns it to the Conn field.
func (o *AccountLimits) SetConn(v int64) {
	o.Conn = &v
}

// GetExports returns the Exports field value if set, zero value otherwise.
func (o *AccountLimits) GetExports() int64 {
	if o == nil || o.Exports == nil {
		var ret int64
		return ret
	}
	return *o.Exports
}

// GetExportsOk returns a tuple with the Exports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetExportsOk() (*int64, bool) {
	if o == nil || o.Exports == nil {
		return nil, false
	}
	return o.Exports, true
}

// HasExports returns a boolean if a field has been set.
func (o *AccountLimits) HasExports() bool {
	if o != nil && o.Exports != nil {
		return true
	}

	return false
}

// SetExports gets a reference to the given int64 and assigns it to the Exports field.
func (o *AccountLimits) SetExports(v int64) {
	o.Exports = &v
}

// GetImports returns the Imports field value if set, zero value otherwise.
func (o *AccountLimits) GetImports() int64 {
	if o == nil || o.Imports == nil {
		var ret int64
		return ret
	}
	return *o.Imports
}

// GetImportsOk returns a tuple with the Imports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetImportsOk() (*int64, bool) {
	if o == nil || o.Imports == nil {
		return nil, false
	}
	return o.Imports, true
}

// HasImports returns a boolean if a field has been set.
func (o *AccountLimits) HasImports() bool {
	if o != nil && o.Imports != nil {
		return true
	}

	return false
}

// SetImports gets a reference to the given int64 and assigns it to the Imports field.
func (o *AccountLimits) SetImports(v int64) {
	o.Imports = &v
}

// GetLeaf returns the Leaf field value if set, zero value otherwise.
func (o *AccountLimits) GetLeaf() int64 {
	if o == nil || o.Leaf == nil {
		var ret int64
		return ret
	}
	return *o.Leaf
}

// GetLeafOk returns a tuple with the Leaf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetLeafOk() (*int64, bool) {
	if o == nil || o.Leaf == nil {
		return nil, false
	}
	return o.Leaf, true
}

// HasLeaf returns a boolean if a field has been set.
func (o *AccountLimits) HasLeaf() bool {
	if o != nil && o.Leaf != nil {
		return true
	}

	return false
}

// SetLeaf gets a reference to the given int64 and assigns it to the Leaf field.
func (o *AccountLimits) SetLeaf(v int64) {
	o.Leaf = &v
}

// GetWildcards returns the Wildcards field value if set, zero value otherwise.
func (o *AccountLimits) GetWildcards() bool {
	if o == nil || o.Wildcards == nil {
		var ret bool
		return ret
	}
	return *o.Wildcards
}

// GetWildcardsOk returns a tuple with the Wildcards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountLimits) GetWildcardsOk() (*bool, bool) {
	if o == nil || o.Wildcards == nil {
		return nil, false
	}
	return o.Wildcards, true
}

// HasWildcards returns a boolean if a field has been set.
func (o *AccountLimits) HasWildcards() bool {
	if o != nil && o.Wildcards != nil {
		return true
	}

	return false
}

// SetWildcards gets a reference to the given bool and assigns it to the Wildcards field.
func (o *AccountLimits) SetWildcards(v bool) {
	o.Wildcards = &v
}

func (o AccountLimits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conn != nil {
		toSerialize["conn"] = o.Conn
	}
	if o.Exports != nil {
		toSerialize["exports"] = o.Exports
	}
	if o.Imports != nil {
		toSerialize["imports"] = o.Imports
	}
	if o.Leaf != nil {
		toSerialize["leaf"] = o.Leaf
	}
	if o.Wildcards != nil {
		toSerialize["wildcards"] = o.Wildcards
	}
	return json.Marshal(toSerialize)
}

type NullableAccountLimits struct {
	value *AccountLimits
	isSet bool
}

func (v NullableAccountLimits) Get() *AccountLimits {
	return v.value
}

func (v *NullableAccountLimits) Set(val *AccountLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountLimits(val *AccountLimits) *NullableAccountLimits {
	return &NullableAccountLimits{value: val, isSet: true}
}

func (v NullableAccountLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


