openapi: 3.0.2
info:
  description: Exchanges OAuth tokens for NATS tokens
  title: Overmind API
  version: "0.2"
servers:
- url: https://api.overmind.tech
paths:
  /healthz:
    get:
      description: Runs a health check
      summary: Health check
      tags:
      - management
  /admin/orgs:
    get:
      description: Lists the details of all orgs within Overmind
      operationId: AdminListOrgs
      security:
      - OAuth2:
        - admin:read
      summary: Orgs - List
      tags:
      - admin
    post:
      description: "Creates a new org, id and public_nkey will be autogenerated"
      operationId: AdminCreateOrg
      security:
      - OAuth2:
        - admin:write
      summary: Orgs - Create
      tags:
      - admin
  /admin/orgs/{org_id}:
    delete:
      description: Deletes an org
      operationId: AdminDeleteOrg
      security:
      - OAuth2:
        - admin:write
      summary: Orgs - Delete
      tags:
      - admin
    get:
      description: Get the details of a given org
      operationId: AdminGetOrg
      security:
      - OAuth2:
        - admin:read
      summary: Orgs - Get details
      tags:
      - admin
    put:
      description: "Update the details of an org, some properties are read only, like\
        \ the org_id"
      operationId: AdminUpdateOrg
      security:
      - OAuth2:
        - admin:write
      summary: Orgs - Update
      tags:
      - admin
  /admin/orgs/{org_id}/sources:
    get:
      description: Lists all sources within a particular org
      operationId: AdminListSources
      security:
      - OAuth2:
        - admin:read
      summary: Sources - List
      tags:
      - admin
    post:
      description: Creates a new source within a given org
      operationId: AdminCreateSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Create
      tags:
      - admin
  /admin/orgs/{org_id}/sources/{source_id}:
    delete:
      description: Deletes a source from an org
      operationId: AdminDeleteSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Delete
      tags:
      - admin
    get:
      description: Gets the details of a source within a given org
      operationId: AdminGetSource
      security:
      - OAuth2:
        - admin:read
      summary: Sources - Get details
      tags:
      - admin
    put:
      description: Updates the details of a source within a given org
      operationId: AdminUpdateSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Update
      tags:
      - admin
  /admin/orgs/{org_id}/tokens:
    post:
      description: Create a new NATS token for a given public NKey. The user requesting
        must control the associated private key also in order to connect to NATS as
        the token is not enough on its own
      operationId: AdminCreateToken
      security:
      - OAuth2:
        - admin:write
        - request:receive
        - request:send
        - reverselink:ingest
        - reverselink:request
        - reverselink:respond
        - gateway:stream
      summary: Generate a NATS token
      tags:
      - admin
  /core/org:
    get:
      description: Get the details of the org that this user belongs to
      operationId: GetOrg
      security:
      - OAuth2:
        - org:read
      summary: Org - Get details
      tags:
      - core
    put:
      description: Updates the details of the org that the user belongs to
      operationId: UpdateOrg
      security:
      - OAuth2:
        - org:write
      summary: Org - Update
      tags:
      - core
  /core/sources:
    get:
      description: Lists all sources within the user's org
      operationId: ListSources
      security:
      - OAuth2:
        - source:read
      summary: Sources - List
      tags:
      - core
    post:
      description: Creates a new source within the user's org
      operationId: CreateSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Create
      tags:
      - core
  /core/sources/{source_id}:
    delete:
      description: Deletes a source from a user's org
      operationId: DeleteSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Delete
      tags:
      - core
    get:
      description: Get the details of a source
      operationId: GetSource
      security:
      - OAuth2:
        - source:read
      summary: Sources - Get details
      tags:
      - core
    put:
      description: Updates the details of a source
      operationId: UpdateSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Update
      tags:
      - core
  /core/tokens:
    post:
      description: Create a new NATS token for a given public NKey. The user requesting
        must control the associated private key also in order to connect to NATS as
        the token is not enough on its own
      operationId: CreateToken
      security:
      - OAuth2:
        - request:receive
        - request:send
        - reverselink:ingest
        - reverselink:request
        - reverselink:respond
        - gateway:stream
      summary: Generate a NATS token
      tags:
      - core
components:
  securitySchemes:
    OAuth2:
      description: Auth0 OAuth
      flows:
        authorizationCode:
          authorizationUrl: https://dev-qsurrmp8.eu.auth0.com/authorization
          scopes:
            admin:read: Read information about all orgs and sources from the admin
              API
            admin:write: Update orgs and sources in the admin API
            org:read: Read information your org
            org:write: "Create, update and delete your org"
            source:read: Read source information
            source:write: "Create, update and delete sources"
            request:receive: Receive requests and respond to them
            request:send: "Ability to send requests to subjects like request.scope.{scope}"
            reverselink:ingest: Ability to communicate with imported requests and
              items subjects from other accounts
            reverselink:request: Can make requests to the revlink service
            reverselink:respond: Can respond to reverse linking requests
            gateway:stream: Can stream gateway responses to be picked up by revlink
          tokenUrl: https://dev-qsurrmp8.eu.auth0.com/oauth/token
        clientCredentials:
          scopes:
            admin:read: Read information about all orgs and sources from the admin
              API
            admin:write: Update orgs and sources in the admin API
            org:read: Read information your org
            org:write: "Create, update and delete your org"
            source:read: Read source information
            source:write: "Create, update and delete sources"
            request:receive: Receive requests and respond to them
            request:send: "Ability to send requests to subjects like request.scope.{scope}"
            reverselink:ingest: Ability to communicate with imported requests and
              items subjects from other accounts
            reverselink:request: Can make requests to the revlink service
            reverselink:respond: Can respond to reverse linking requests
            gateway:stream: Can stream gateway responses to be picked up by revlink
          tokenUrl: https://dev-qsurrmp8.eu.auth0.com/oauth/token
      type: oauth2
