openapi: 3.0.2
info:
  description: API for managing your Overmind account
  title: Overmind API
  version: "0.2"
servers:
- url: https://api.overmind.tech
paths:
  /healthz:
    get:
      description: Runs a health check
      summary: Health check
      tags:
      - management
  /admin/accounts:
    get:
      description: Lists the details of all NATS Accounts
      operationId: AdminListAccounts
      security:
      - OAuth2:
        - admin:read
      summary: Accounts - List
      tags:
      - admin
    post:
      description: "Creates a new account, public_nkey will be autogenerated"
      operationId: AdminCreateAccount
      security:
      - OAuth2:
        - admin:write
      summary: Accounts - Create
      tags:
      - admin
  /admin/accounts/{account_name}:
    delete:
      description: Deletes an account
      operationId: AdminDeleteAccount
      security:
      - OAuth2:
        - admin:write
      summary: Accounts - Delete
      tags:
      - admin
    get:
      description: Get the details of a given account
      operationId: AdminGetAccount
      security:
      - OAuth2:
        - admin:read
      summary: Accounts - Get details
      tags:
      - admin
  /admin/accounts/{account_name}/sources:
    get:
      description: Lists all sources within a particular account
      operationId: AdminListSources
      security:
      - OAuth2:
        - admin:read
      summary: Sources - List
      tags:
      - admin
    post:
      description: Creates a new source within a given account
      operationId: AdminCreateSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Create
      tags:
      - admin
  /admin/accounts/{account_name}/sources/{source_id}:
    delete:
      description: Deletes a source from an account
      operationId: AdminDeleteSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Delete
      tags:
      - admin
    get:
      description: Gets the details of a source within a given account
      operationId: AdminGetSource
      security:
      - OAuth2:
        - admin:read
      summary: Sources - Get details
      tags:
      - admin
    put:
      description: Updates the details of a source within a given account
      operationId: AdminUpdateSource
      security:
      - OAuth2:
        - admin:write
      summary: Sources - Update
      tags:
      - admin
  /admin/accounts/{account_name}/tokens:
    post:
      description: Create a new NATS token for a given public NKey. The user requesting
        must control the associated private key also in order to connect to NATS as
        the token is not enough on its own
      operationId: AdminCreateToken
      security:
      - OAuth2:
        - admin:write
        - request:receive
        - request:send
        - reverselink:ingest
        - reverselink:request
        - reverselink:respond
        - gateway:stream
      summary: Generate a NATS token
      tags:
      - admin
  /core/account:
    get:
      description: Get the details of the account that this user belongs to
      operationId: GetAccount
      security:
      - OAuth2:
        - account:read
      summary: Account - Get details
      tags:
      - core
  /core/sources:
    get:
      description: Lists all sources within the user's account
      operationId: ListSources
      security:
      - OAuth2:
        - source:read
      summary: Sources - List
      tags:
      - core
    post:
      description: Creates a new source within the user's account
      operationId: CreateSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Create
      tags:
      - core
  /core/sources/{source_id}:
    delete:
      description: Deletes a source from a user's account
      operationId: DeleteSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Delete
      tags:
      - core
    get:
      description: Get the details of a source
      operationId: GetSource
      security:
      - OAuth2:
        - source:read
      summary: Sources - Get details
      tags:
      - core
    put:
      description: Updates the details of a source
      operationId: UpdateSource
      security:
      - OAuth2:
        - source:write
      summary: Sources - Update
      tags:
      - core
  /core/tokens:
    post:
      description: Create a new NATS token for a given public NKey. The user requesting
        must control the associated private key also in order to connect to NATS as
        the token is not enough on its own
      operationId: CreateToken
      security:
      - OAuth2:
        - request:receive
        - request:send
        - reverselink:ingest
        - reverselink:request
        - reverselink:respond
        - gateway:stream
      summary: Generate a NATS token
      tags:
      - core
components:
  securitySchemes:
    OAuth2:
      description: Auth0 OAuth
      flows:
        authorizationCode:
          authorizationUrl: https://dev-qsurrmp8.eu.auth0.com/authorization
          scopes:
            admin:read: Read information about all accounts and sources from the admin
              API
            admin:write: Update accounts and sources in the admin API
            account:read: Read information about your account
            source:read: Read source information
            source:write: "Create, update and delete sources"
            request:receive: Receive requests and respond to them
            request:send: "Ability to send requests to subjects like request.scope.{scope}"
            reverselink:ingest: Ability to communicate with imported requests and
              items subjects from other accounts
            reverselink:request: Can make requests to the revlink service
            reverselink:respond: Can respond to reverse linking requests
            gateway:stream: Can stream gateway responses to be picked up by revlink
          tokenUrl: https://dev-qsurrmp8.eu.auth0.com/oauth/token
        clientCredentials:
          scopes:
            admin:read: Read information about all accounts and sources from the admin
              API
            admin:write: Update accounts and sources in the admin API
            account:read: Read information about your account
            source:read: Read source information
            source:write: "Create, update and delete sources"
            request:receive: Receive requests and respond to them
            request:send: "Ability to send requests to subjects like request.scope.{scope}"
            reverselink:ingest: Ability to communicate with imported requests and
              items subjects from other accounts
            reverselink:request: Can make requests to the revlink service
            reverselink:respond: Can respond to reverse linking requests
            gateway:stream: Can stream gateway responses to be picked up by revlink
          tokenUrl: https://dev-qsurrmp8.eu.auth0.com/oauth/token
      type: oauth2
